dist: trusty
sudo: required

language: c++

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=RELEASE

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libelf-dev cmake3

install:
  - wget https://github.com/openrisc/newlib/releases/download/v2.4.0/or1k-elf_gcc5.3.0_binutils2.26_newlib2.4.0_gdb7.11.tgz
  - tar -xzf or1k-elf_gcc5.2.0_binutils2.26_newlib2.3.0-1_gdb7.11.tgz
  - export PATH=$PATH:`pwd`/or1k-elf/bin
  - or1k-elf-gcc --version

before_script:
  - mkdir BUILD
  - cd BUILD
  - cmake .. -DBUILD_SW=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - make && ctest --output-on-failure
