dist: trusty
sudo: false

language: c++

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libelf-dev

env:
  - BUILD=RELEASE

install:
  - release=or1k-elf_gcc5.3.0_binutils2.26_newlib2.4.0_gdb7.11.tgz
  - wget https://github.com/openrisc/newlib/releases/download/v2.4.0/$release
  - tar -xzf $release
  - export PATH=$PATH:`pwd`/or1k-elf/bin
  - or1k-elf-gcc --version

before_script:
  - mkdir BUILD && cd BUILD
  - cmake .. -DBUILD_SW=ON -DCMAKE_BUILD_TYPE=$BUILD

script:
  - make && ctest --output-on-failure
