dist: trusty
sudo: required

language: c++

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libelf-dev cmake3

install:
  - wget https://github.com/openrisc/newlib/releases/download/v2.3.0-1/or1k-elf_gcc5.2.0_binutils2.26_newlib2.3.0-1_gdb7.11.tgz
  - tar -xzvf or1k-elf_gcc5.2.0_binutils2.26_newlib2.3.0-1_gdb7.11.tgz
  - export PATH=$PATH:`pwd`/or1k-elf/bin

before_script:
  - mkdir BUILD
  - cd BUILD
  - cmake .. -DBUILD_SW=ON

script: make
